### ISSUE TITLE
Timer do not stop when notify open as expected

### ISSUE THREAD

**Issue by Asthestarsfalll** [mvllow/stand.nvim#1] opened 2023-07-21 11:30 UTC
```lua
		vim.notify(" ⏰ Time to stand ", vim.log.levels.WARN, {
			title = "stand.nvim",
			render = "minimal",
			timeout = false,
			on_open = function()
				timer:stop()
			end,
			on_close = function()
				timer:again()
			end,
		})
```
It should be stoped when notify popup, but I find it still timing. 
![2023-07-21_19-28](https://github.com/mvllow/stand.nvim/assets/72954905/9b431ad0-0658-4f65-9518-96d63c72bdff)

**Comment by mvllow** [comment] 2023-07-21 11:54
Hmm, I'm unable to reproduce on Neovim nightly. When setting `minute_interval = 0.1` (6 seconds), I get one notification and another doesn't appear until another 6 seconds _after_ closing either via `:StandNow` or `:bd` when focused on the notification.

Edit: I'm not too familiar with nvim-notify but do you have any user configuration for that plugin that could be interfering?

**Comment by Asthestarsfalll** [comment] 2023-07-21 12:04
I also can't reproduce this with a minimal init.lua, maybe there are some confilcting configurations

**Closed as completed** 2023-07-21 12:07 UTC

**Comment by Asthestarsfalll** [comment] 2023-07-21 13:42
By the way, inspired by stand.nvim, I adapt stand.nvim into  [clock.nvim](https://github.com/Asthestarsfalll/clock.nvim)  to support customize different events and some other ambitious
